#!/bin/bash

function check_for_file() {
  local repo
  local file
  repo="$1"
  file="$2"
  if ! curl "https://raw.githubusercontent.com/samchristywork/$repo/main/$file" \
    -s -f > /dev/null; then
    printf "| "
  else
    printf "|X"
  fi
}

(
echo "Name|README.md|CONTRIBUTING.md"
echo "----|---------|---------------"

while read -r repo; do
  printf "$repo"
  check_for_file "$repo" "README.md"
  check_for_file "$repo" "CONTRIBUTING.md"
  echo
  sleep 1
done
) | column -t -s '|'
